--
DECLARE @LTB FLOAT
SET @LTB = (SELECT AVG(LUONG) FROM NHANVIEN)
SELECT IIF(LUONG>@LTB,'truong phong','pho phong' ) 
AS ChucVu,TENNV,Luong FROM NHANVIEN

go
--
SELECT TENNV = CASE PHAI
WHEN N'nam' then 'Mr '+[TENNV]
WHEN N'Nữ'  then 'Ms '+ [TENNV]
ELSE TENNV
end
FROM NHANVIEN

----

SELECT * FROM NHANVIEN
SELECT TENNV , LUONG, 'THUE'=
	CASE
	WHEN LUONG between 0 and 25000 then LUONG * (10/100)
	WHEN LUONG between 25000 and 30000 then LUONG *(12/100)
	WHEN LUONG between 30000 and 40000 then LUONG *(15/100)
	WHEN LUONG between 40000 and 50000 then LUONG *(20/100)
	ELSE LUONG * (25/100)
	 END
	 FROM NHANVIEN
