DECLARE @LUONG FLOAT
SET @LUONG = (SELECT AVG(LUONG)
				FROM NHANVIEN, PHONGBAN
				WHERE NHANVIEN.PHG = PHONGBAN.MAPHG)

SELECT TENNV, IIF(LUONG < @LUONG, 'TÃNG LÝÕNG', 'KHÔNG TÃNG LÝÕNG') AS 'XEM XÉT TÃNG LÝÕNG'
FROM NHANVIEN