DECLARE @LUONG FLOAT
SET @LUONG = (SELECT AVG(LUONG)
				FROM NHANVIEN, PHONGBAN
				WHERE NHANVIEN.PHG = PHONGBAN.MAPHG)

SELECT TENNV, IIF(LUONG < @LUONG, N'Tăng lương', N'Không tăng lương') AS N'xem xet tăng lương'
FROM NHANVIEN
